# Generated by Django 5.1.6 on 2025-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
